/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'beshort' at '5/30/17 11:52 PM' with Gradle 2.14.1
 *
 * @author beshort, @date 5/30/17 11:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
